### ISSUE TITLE
Проблемы с разделом "начинаем работу с симфони"

### ISSUE THREAD

**Issue by egolife** [EvercodeLab/thebookofknowledge#21]
https://github.com/EvercodeLab/thebookofknowledge/tree/master/symfony_start
Когда переходим по ссылке из содержания - 
не виден контент (как на других страницах)
Вместо этого только файл.

**Comment by BelkinaDasha** [comment]
@egolife Ты можешь сам сделать README файл в этой директории при желании

**Comment by memphys** [comment]
там Серёга как раз в пулле про ревью обновляет структуру раздела. Думаю, можно сразу там привести всё в порядок)

**Comment by sergeylunev** [comment]
@egolife @memphys я вроде уже привёл.

**Comment by sergeylunev** [comment]
@egolife @memphys точно привёл.
